version: 1
robots:
  X5:
    joint_dof: 6
    joint_pos_min: [-3.14, -0.05, -0.1, -1.6, -1.57, -2.0]
    joint_pos_max: [2.618, 3.50, 3.20, 1.55, 1.57, 2.0]
    joint_vel_max: [5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 4, 5, 6, 7]
    motor_type: [EC_A4310, EC_A4310, EC_A4310, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.088, open_readout: 3.59549, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/X5.urdf
  X5_umi:
    joint_dof: 6
    joint_pos_min: [-3.14, -0.05, -0.1, -1.6, -1.57, -2.0]
    joint_pos_max: [2.618, 3.50, 3.20, 1.55, 1.57, 2.0]
    joint_vel_max: [5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 4, 5, 6, 7]
    motor_type: [EC_A4310, EC_A4310, EC_A4310, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.086, open_readout: 4.90, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/X5_umi.urdf
  X5_iphumi:
    joint_dof: 6
    joint_pos_min: [-3.14, -0.05, -0.1, -1.6, -1.57, -2.0]
    joint_pos_max: [2.618, 3.50, 3.20, 1.55, 1.57, 2.0]
    joint_vel_max: [5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 4, 5, 6, 7]
    motor_type: [EC_A4310, EC_A4310, EC_A4310, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.086, open_readout: 4.90, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/X5_iphumi.urdf
  L5:
    joint_dof: 6
    joint_pos_min: [-3.14, -0.05, -0.1, -1.6, -1.57, -2.0]
    joint_pos_max: [2.618, 3.50, 3.20, 1.55, 1.57, 2.0]
    joint_vel_max: [5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 4, 5, 6, 7]
    motor_type: [DM_J4340, DM_J4340, DM_J4340, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.088, open_readout: 5.03, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/L5.urdf
  L5_umi:
    joint_dof: 6
    joint_pos_min: [-3.14, -0.05, -0.1, -1.6, -1.57, -2.0]
    joint_pos_max: [2.618, 3.50, 3.20, 1.55, 1.57, 2.0]
    joint_vel_max: [5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 4, 5, 6, 7]
    motor_type: [DM_J4340, DM_J4340, DM_J4340, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.086, open_readout: 4.90, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/L5_umi.urdf
  L5_iphumi:
    joint_dof: 6
    joint_pos_min: [-3.14, -0.05, -0.1, -1.6, -1.57, -2.0]
    joint_pos_max: [2.618, 3.50, 3.20, 1.55, 1.57, 2.0]
    joint_vel_max: [5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 4, 5, 6, 7]
    motor_type: [DM_J4340, DM_J4340, DM_J4340, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.086, open_readout: 4.90, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/L5_iphumi.urdf
  X7_left:
    joint_dof: 7
    joint_pos_min: [-2.09439, -1.5, -1.5, -1.5, -1.2, -0.3, -0.7854]
    joint_pos_max: [2.09439, 0.3, 1.5, 0.3, 1.2, 0.7854, 0.7854]
    joint_vel_max: [3.0, 5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 3, 4, 5, 6, 7]
    motor_type: [DM_J4340, DM_J4340, DM_J4340, DM_J4340, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.088, open_readout: 5.03, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/X7_left.urdf
  X7_right:
    joint_dof: 7
    joint_pos_min: [-2.09439, -0.3, -1.5, -0.3, -1.2, -0.7854, -0.7854]
    joint_pos_max: [2.09439, 1.5, 1.5, 1.5, 1.2, 0.3, 0.7854]
    joint_vel_max: [3.0, 5.0, 5.0, 5.5, 5.5, 5.0, 5.0]
    joint_torque_max: [30.0, 30.0, 40.0, 30.0, 15.0, 10.0, 10.0]
    ee_vel_max: [0.6, 0.6, 0.6, 1.8, 1.8, 1.8]
    motor_id: [1, 2, 3, 4, 5, 6, 7]
    motor_type: [DM_J4340, DM_J4340, DM_J4340, DM_J4340, DM_J4310, DM_J4310, DM_J4310]
    gripper: {vel_max: 0.3, torque_max: 1.5, width: 0.088, open_readout: 5.03, motor_id: 8, motor_type: DM_J4310}
    gravity_vector: [0.0, 0.0, -9.807]
    base_link_name: base_link
    eef_link_name: eef_link
    urdf_path: ../models/X7_right.urdf
controllers:
  joint_controller:
    "6": {default_kp: [80.0, 70.0, 70.0, 30.0, 30.0, 20.0], default_kd: [2.0, 2.0, 2.0, 1.0, 1.0, 0.7], default_gripper_kp: 5.0, default_gripper_kd: 0.2, over_current_cnt_max: 20, controller_dt: 0.002, gravity_compensation: true, background_send_recv: true, shutdown_to_passive: true, interpolation_method: linear, default_preview_time: 0.0}
    "7": {default_kp: [80.0, 70.0, 70.0, 70.0, 30.0, 30.0, 20.0], default_kd: [2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 0.7], default_gripper_kp: 5.0, default_gripper_kd: 0.2, over_current_cnt_max: 20, controller_dt: 0.002, gravity_compensation: true, background_send_recv: true, shutdown_to_passive: true, interpolation_method: linear, default_preview_time: 0.0}
  cartesian_controller:
    "6": {default_kp: [200.0, 200.0, 200.0, 120.0, 80.0, 60.0], default_kd: [5.0, 5.0, 5.0, 1.0, 1.0, 1.0], default_gripper_kp: 5.0, default_gripper_kd: 0.2, over_current_cnt_max: 20, controller_dt: 0.002, gravity_compensation: true, background_send_recv: true, shutdown_to_passive: true, interpolation_method: linear, default_preview_time: 0.1}
    "7": {default_kp: [300.0, 300.0, 300.0, 300.0, 80.0, 50.0, 40.0], default_kd: [5.0, 5.0, 5.0, 5.0, 1.0, 1.0, 1.0], default_gripper_kp: 5.0, default_gripper_kd: 0.2, over_current_cnt_max: 20, controller_dt: 0.002, gravity_compensation: true, background_send_recv: true, shutdown_to_passive: true, interpolation_method: linear, default_preview_time: 0.1}
